cameracollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('cameras/', views.cameras_index, name='index'),
    path('cameras/<int:camera_id>', views.cameras_detail, name='detail'),
    path('cameras/create/', views.CameraCreate.as_view(), name='cameras_create'),
    path('cameras/<int:pk>/update', views.CameraUpdate.as_view(), name='cameras_update'),
    path('cameras/<int:pk>/delete/', views.CameraDelete.as_view(), name='cameras_delete'),
    path('cameras/<int:camera_id>/add_recall/', views.add_recall, name='add_recall'),
    path('lenses/', views.LensList.as_view(), name='lenses_index'),
    path('lenses/<int:pk>/', views.LensDetail.as_view(), name='lenses_detail'),
    path('lenses/create/', views.LensCreate.as_view(), name='lenses_create'),
    path('lenses/<int:pk>/update/', views.LensUpdate.as_view(), name='lenses_update'),
    path('lenses/<int:pk>/delete/', views.LensDelete.as_view(), name='lenses_delete'),
    path('cameras/<int:camera_id>/assoc_lens/<int:lens_id>/', views.assoc_lens, name='assoc_lens'),
    path('cameras/<int:camera_id>/add_photo/', views.add_photo, name='add_photo'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
# Create your models here.

DEGREES = (
    ('MN', 'Minor'),
    ('MJ', 'Major')
)

class Lens(models.Model):
    name = models.CharField(max_length=20)
    lens_mount = models.CharField(max_length=50)
    focal_length = models.CharField(max_length=50)
    aperture = models.CharField(max_length=30)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('lenses_detail', kwargs={'pk': self.id})

    
class Camera(models.Model):
    name = models.CharField(max_length=100)
    brand = models.CharField(max_length=100)
    lens_mount = models.CharField(max_length=50)
    sensor = models.CharField(max_length=50)
    resolution = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField(max_length=250)
    lens = models.ManyToManyField(Lens)
    user = models.ManyToManyField(User)
    
    def __str__(self):
        return f"{self.brand} {self.name}"

    def get_absolute_url(self):
        return reverse('detail', kwargs={'camera_id': self.id})


class Recall(models.Model):
    date = models.DateField('Recall Date')
    degree = models.CharField(
        max_length=2,
        choices=DEGREES,
        default=DEGREES[0][0]
    )

    camera = models.ForeignKey(Camera, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_degree_display()} recall on {self.date}"

    class Meta:
        ordering = ['-date']
    
class Photo(models.Model):
    url = models.CharField(max_length=200)
    camera = models.ForeignKey(Camera, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for camera_id: {self.camera_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Recall

class RecallForm(ModelForm):
  class Meta:
    model = Recall
    fields = ['date', 'degree']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
import uuid
import boto3
from .models import Camera, Lens, Recall, Photo
from .forms import RecallForm

S3_BASE_URL = 'https://s3-us-west-1.amazonaws.com/'
BUCKET = 'cameracollector'

# Define the home view
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def cameras_index(request):
    cameras = Camera.objects.all()
    return render(request, 'cameras/index.html', { 'cameras': cameras })

def cameras_detail(request, camera_id):
    camera = Camera.objects.get(id=camera_id)
    lens_camera_doesnt_have = Lens.objects.exclude(id__in = camera.lens.all().values_list('id'))

    recall_form = RecallForm()

    return render(request, 'cameras/detail.html', { 
        'camera': camera, 
        'recall_form': recall_form,
        'lens': lens_camera_doesnt_have
    })

def add_recall(request, camera_id):
    form = RecallForm(request.POST)
     # validate the form
    if form.is_valid():
    # don't save the form to the db until it
    # has the cat_id assigned
        new_recall = form.save(commit=False)
        new_recall.camera_id = camera_id
        new_recall.save()
    return redirect('detail', camera_id=camera_id)

class CameraCreate(CreateView):
    model = Camera
    fields = '__all__'
    success_url = '/cameras/'

class CameraUpdate(UpdateView):
    model = Camera
    fields = '__all__'

class CameraDelete(DeleteView):
    model = Camera
    success_url = '/cameras/'

class LensList(ListView):
  model = Lens

class LensDetail(DetailView):
  model = Lens

class LensCreate(CreateView):
  model = Lens
  fields = '__all__'

class LensUpdate(UpdateView):
  model = Lens
  fields = ['name', 'lens_mount', 'focal_length', 'aperture']

class LensDelete(DeleteView):
  model = Lens
  success_url = '/lenses/'

def assoc_lens(request, camera_id, lens_id):
  # Note that you can pass a toy's id instead of the whole object
  Camera.objects.get(id=camera_id).lens.add(lens_id)
  return redirect('detail', camera_id=camera_id)

def add_photo(request, camera_id):
    # photo-file will be the "name" attribute on the <input type="file">
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        # need a unique "key" for S3 / needs image file extension too
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        # just in case something goes wrong
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            # build the full url string
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            # we can assign to cat_id or cat (if you have a cat object)
            Photo.objects.create(url=url, camera_id=camera_id)
        except:
            print('An error occurred uploading file to S3')
    return redirect('detail', camera_id=camera_id)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Camera Collector</h1>
<hr />
<p>Hire the Camera Collector!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Camera Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;Camera Collector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          {% if user.is_authenticated %}
          <li><a href="{% url 'lenses_create' %}">Add a Lens</a></li>
          <li><a href="{% url 'lenses_index' %}">View All Lenses</a></li>
          <li><a href="{% url 'cameras_create' %}">Add a Camera</a></li>
          <li><a href="{% url 'index' %}">View All Cameras</a></li>
          <li><a href="{% url 'logout' %}">Log Out</a></li>
          {% else %}
          <li><a href="{% url 'login' %}">Log In</a></li>      
          {% endif %}
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2022 Camera Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/cameras/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Camera Details</h1>
{% for photo in camera.photo_set.all %}
    <img class="responsive-img card-panel" src="{{photo.url}}">
    {% empty %}
      <div class="card-panel teal-text center-align">No Photos Uploaded</div>
    {% endfor %}
<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ camera.name }}</span>
        <p>Brand: {{ camera.brand }}</p>
        <p>Mount: {{ camera.lens_mount }}</p>
        <p>Description: {{ camera.description }}</p>
        <p>Sensor: {{ camera.sensor }}</p>
        <p>Resolution: {{ camera.resolution }} mp</p>
      </div>
      <div class="card-action">
        <a href="{% url 'cameras_update' camera.id %}">Edit</a>
        <a href="{% url 'cameras_delete' camera.id %}">Delete</a>
      </div>
  </div>
</div>
  <div class="col s6">
    <form action="{% url 'add_recall' camera.id %}" method="post">
      {% csrf_token %}
      {{ recall_form.as_p }}
      <input type="submit" class="btn" value="Add Recall">
    </form>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Recall</th></tr>
      </thead>
      <tbody>
        {% for recall in camera.recall_set.all %}
          <tr>
            <td>{{recall.date}}</td>
            <td>{{recall.degree}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div>
    

    <form action="{% url 'add_photo' camera.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
      {% csrf_token %}
      <input type="file" name="photo-file">
      <br><br>
      <input type="submit" class="btn" value="Upload Photo">
    </form>
  </div>
</div>


  <hr>
  <div class="row">
    <div class="col s6">
      <h3>{{ camera.name }}'s Lenses</h3>
      {% if camera.lens.count %}
        {% for lens in camera.lens.all %}
          <div class="card">
            <div class="card-content">
              <span class="card-title">
                {{ lens.brand}} {{ lens.name }} {{ lens.focal_length }} {{ lens.aperture}}
              </span>
            </div>
          </div>
        {% endfor %}
      {% else %}
        <h5>No Lenses</h5>
      {% endif %}
    </div>
    <div class="col s6">
      <h3>Available Lenses</h3>
      {% if lens.count %}
        {% for lens in lens.all %}
          <div class="card">
            <div class="card-content">
              <span class="card-title">
                {{ lens.brand}} {{ lens.name }} {{ lens.focal_length }} {{ lens.aperture}}
              </span>
            </div>
            <div class="card-action">
              <form action="{% url 'assoc_lens' camera.id lens.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn">Add</button>
              </form>
            </div>
          </div>
        {% endfor %}
      {% else %}
        <h5>{{camera.name}} Already Has All Lenses Available</h5>
      {% endif %}
</div>

<script>
  const dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

  const selectEl = document.getElementById('id_degree');
  M.FormSelect.init(selectEl);
</script>

{% endblock %}

main_app/templates/cameras/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Camera List</h1>

{% for camera in cameras %}
<a href="{% url 'detail' camera.id %}">
  <div class="card">
    <div class="card-content">
      <span class="card-title">{{ camera.name }}</span>
      <p>Brand: {{ camera.brand }}</p>
      <p>Description: {{ camera.description }}</p>

    </div>
  </div>
</a>
{% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Home</h1>

{% endblock %}

main_app/templates/main_app/camera_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Camera</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' camera.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/camera_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
    {% else %}
    <h1>Add Camera</h1>
    {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/lens_confirm_delete.html
  
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Lens</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'lenses_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/lens_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Lens Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ lens.name }}</span>
        <p>Lens Mount: {{ lens.lens_mount }}</p>
        <p>Focal Length: {{ lens.focal_length }}</p>
        <p>Aperture: {{ lens.aperture }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'lenses_update' lens.id %}">Edit</a>
        <a href="{% url 'lenses_delete' lens.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/lens_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Lens</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/lens_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Lens List</h1>

{% for lens in lens_list %}
  <a href="{% url 'lenses_detail' lens.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ lens.name }}</span>
            <p>Lens Mount: {{ lens.lens_mount }}</p>
            <p>Focal Length: {{ lens.focal_length }}</p>
            <p>Aperture: {{ lens.aperture }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}